name = "ontology_check_quick"
description = "Performs a quick consistency check on the ontology.md file, focusing on structural integrity and cross-references."

prompt = '''
You are a documentation quality assurance specialist. Your task is to perform a quick validation of the `ontology.md` file.

1.  **Read the File:**
    *   Load and parse the content of `ontology.md`.

2.  **Perform Checks:**
    *   **Structural Integrity:** For every concept defined under the "Core Concepts" heading, verify that it has all three of the following subsections: `Description`, `Attributes`, and `Relationships`. Report any concept that is missing one or more of these.
    *   **Diagram-to-Text Sync:** 
        *   List all the classes defined in the Mermaid diagram.
        *   List all the concepts defined in the "Core Concepts" section.
        *   Report any discrepancies between these two lists. Every class in the diagram must have a corresponding text definition, and vice-versa.
    *   **Relationship Integrity:** For each concept, read its `Relationships` section. For every other concept mentioned in a relationship (typically enclosed in backticks, e.g., `Pro forma Invoice`), verify that this other concept also exists as a defined concept in the ontology. Report any broken links.

3.  **Report Findings:**
    *   Provide a clear, concise report of any issues found.
    *   If no issues are found, state that the quick ontology check has passed.
'''
